INSERT INTO "User" (id, email, password, name, "quizCompleted", "updatedAt") VALUES (1, 'admin@propertylo.com', 'hash', 'System Admin', false, CURRENT_TIMESTAMP);
INSERT INTO "Property" (id, title, description, address, city, locality, "areaSqFt", price, type, "propertyType", bhk, "imageUrls", "isVerified", "isGated", "furnishedStatus", "category", "uploaderId", "updatedAt", "possessionStatus", "listingType", "isNewLaunch", "isNewBooking", "petFriendly", "nearSchool", "nearPark", "nearMetro", "nearHospital", "views") VALUES (1, '3 BHK Serviced Apartment for rent in Hiranandani Gardens Powai, Mumbai', 'This apartment is a fully furnished fixed company that is allowed additional 12k approx monthly payment to society property is located in proper hirnandani.', '3 BHK Serviced Apartment for rent in Hiranandani Gardens Powai, Mumbai', 'Nagpur', 'Nagpur', 1100, 0, 'RENT', 'Serviced Apartment', '3BHK', '[]', true, true, 'Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(2, '3 BHK Serviced Apartment for rent in Deonar, Chembur East', 'Independent bungalow for rent on ground floor specious flat on rent at deonar near ccday.', '3 BHK Serviced Apartment for rent in Deonar, Chembur East', 'Nagpur', 'Nagpur', 2000, 0, 'RENT', 'Serviced Apartment', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(3, '1 BHK Flat for rent in Laxmi Nagar, Vikhroli East', 'This flat consists of 1 bathroom build in 497 sq.Ft. Super built-Up area. The flat is built on 497 sq.Ft. Area. This flat is situated at ground in a tower with 1 floor. This is a 0-1 year old society. It is a semi-Furnished property. Inclusive of 1 light. The flat will be available from wed, 01 apr 2026 for family on any agreement type. With all the highlighted features, we are asking for 30,00...', '1 BHK Flat for rent in Laxmi Nagar, Vikhroli East', 'Nagpur', 'Nagpur', 497, 0, 'RENT', 'Flat', '1BHK', '[]', true, true, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(4, '1 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Located in garodia nagar, ghatkopar east, this furnished 1 bhk flat spans 570 sq.Ft. On the 3rd floor of a low-Rise building. Aged over 10 years, it features mosaic flooring and central air conditioning. Ready for rent from june 15, 2026, the top-Floor apartment offers proximity to key religious sites and eye essential hospital.', '1 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Nagpur', 'Nagpur', 570, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(5, '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'Available from april 25, 2026, this 1 bhk flat on the 7th floor of a 17-Story high-Rise at aaradhya one earth b, ghatkopar east offers 480 sq.Ft. Of semi-Furnished living space. East-Facing with a modular kitchen, it includes amenities like a gym, pool, parking, and lift, close to markets, railway station, and healthcare facilities.', '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'Nagpur', 'Nagpur', 480, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(6, '2 BHK Flat for rent in Khalai Village, Vidyavihar, Mumbai', 'Well maintained club house & sprawling garden. Spacious room looking at open spaces', '2 BHK Flat for rent in Khalai Village, Vidyavihar, Mumbai', 'Nagpur', 'Nagpur', 681, 0, 'RENT', 'Villa', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(7, '2 BHK Flat for rent in Vikhroli West, Mumbai', 'A spacious 2 bhk flat for rent is available in vikhroli west in laxmi heights, central mumbai. Property has attached 2 bathrooms with 2 rooms set in 727 sq.Ft. Carpet area. The flat consists of 2 bedrooms, built on 727 sq.Ft. The building has a total of 17 floors and this property is situated on 6th floor. Property is 0-1 year old. This property is semi-Furnished. Equipped with 1 water purifier...', '2 BHK Flat for rent in Vikhroli West, Mumbai', 'Nagpur', 'Nagpur', 727, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(8, '1 BHK Flat for rent in Bhandup West, Mumbai', 'Gym - Free in premises,
Market - 200 meter''s , 
Banks - 350 meter,
School - 1km, 
College - 1km,
Atm - 200 meter, 
Hoapital & clinic - 200 meter, 
Railway station - 2.5 km
Mall - 2 km
Cinema hall - 2 km', '1 BHK Flat for rent in Bhandup West, Mumbai', 'Nagpur', 'Nagpur', 323, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(9, '1 BHK Flat for rent in Tagore Nagar, Vikhroli East', 'Fresh air, garden facing, 24 hours water supply, no power outage', '1 BHK Flat for rent in Tagore Nagar, Vikhroli East', 'Nagpur', 'Nagpur', 500, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(10, '2 BHK Flat for rent in Chandivali, Mumbai', 'Situated on the 1st floor of a 19-Story high-Rise in chandivali, mumbai, this furnished 2 bhk flat spans 1105 sq.Ft. Featuring 2 bedrooms and 2 bathrooms, the apartment offers immediate availability. Residents enjoy amenities like a gym, swimming pool, power backup, and proximity to saki naka metro and phoenix marketcity mall.', '2 BHK Flat for rent in Chandivali, Mumbai', 'Nagpur', 'Nagpur', 1105, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(11, '1 BHK Flat for rent in Ghatkopar West, Mumbai', 'I want to rent out a 1 bhk apartment available in sri 86 central,ghatkopar west, central mumbai.Located in a serene place, it has a carpet area of 300 sq.Ft. It is an attractive property. The property has an amazing location and is unfurnished.It has 1 balcony(s) which offer an excellent view.', '1 BHK Flat for rent in Ghatkopar West, Mumbai', 'Nagpur', 'Nagpur', 300, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(12, '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'Offering a 1 bhk flat spanning 360 sq.Ft. On the 1st floor of a low-Rise building in vikrant apartment, ghatkopar east, central mumbai. This 1-5 year old, semi-Furnished residence features 1 bedroom and 1 bathroom, available for immediate rent at rs 5000. Conveniently located near religious sites and quality healthcare facilities.', '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'Nagpur', 'Nagpur', 360, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(13, '2 BHK Flat for rent in Chandivali, Mumbai', 'Located in palatial heights, chandivali, this 2 bhk flat offers 700 sq.Ft. Of semi-Furnished living space on the 2nd floor of a 15-Story high-Rise. With 2 bedrooms and 2 bathrooms, it is over 10 years old and available for immediate rent. Conveniently close to multiple atms and hospitals, this residential apartment suits those seeking central mumbai living.', '2 BHK Flat for rent in Chandivali, Mumbai', 'Nagpur', 'Nagpur', 700, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(14, '1 BHK Flat for rent in Kurla East, Mumbai', 'This property offers access to nearby landmarks and is close to school, close to hospital, close to market and close to railway station. This flat consists of 2 bathrooms build in 427 sq.Ft. Carpet area. The flat is built on 427 sq.Ft. Area. This property has others as well. Ease of access to 1 open parking within society. This flat is situated at 9th in a tower with 19 floors. This is a 0-1 ye...', '1 BHK Flat for rent in Kurla East, Mumbai', 'Nagpur', 'Nagpur', 427, 0, 'RENT', 'Flat', '1BHK', '[]', true, true, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(15, '2 BHK Flat for rent in Vikhroli East, Mumbai', 'Building name (Adityaraj shivraj) it''s 2bhk flat on 12th floor.. At best location totally new untouched flat near 1mint walking eastern highway, school, hospital bus rikshaw stand everything is near by 5mint', '2 BHK Flat for rent in Vikhroli East, Mumbai', 'Nagpur', 'Nagpur', 5920, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(16, '2 BHK Flat for rent in Powai, Mumbai', 'Located on the 10th floor of a high-Rise in suncity complex, powai, this 1-5 year old 2 bhk flat offers 650 sq.Ft. Of semi-Furnished living space. Featuring 2 bedrooms, 2 bathrooms, and amenities like a clubhouse, lift, and power backup, its vaastu compliant and ready for immediate move-In. Close to saki naka metro and key educational centers.', '2 BHK Flat for rent in Powai, Mumbai', 'Nagpur', 'Nagpur', 650, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(17, '2 BHK Flat for rent in dombivali east, Mumbai', 'Premium 1/2/3 bhk apartment for sale/rent in prime location Discover your dream home in a well-Planned and premium residential project by lodha group, offering modern living with world-Class amenities. This spacious and well-Ventilated apartment is thoughtfully designed with ample natural light and a smart layout, ensuring maximum comfort and functionality. Located in a prime area, the property...', '2 BHK Flat for rent in dombivali east, Mumbai', 'Nagpur', 'Nagpur', 540, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(18, '2 BHK Flat for rent in Mulund West, Mumbai', 'Premium 2 bhk for rent in piramal revanta tower 4 , mulund west. Higherfloor apartment with uninterrupted sgnp views from all rooms. Bright, welllit home with living room & deck. Semifurnished with acs in all rooms, geysers, semimodular kitchen, smart home automation, wifi, invisible grills & dedicated parking. Vaastu compliant. Im available on (Whatsapp only)', '2 BHK Flat for rent in Mulund West, Mumbai', 'Nagpur', 'Nagpur', 620, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(19, '1 BHK Flat for rent in Lallubhai Compound, Govandi East, Mumbai', 'Spacious 1bhk flat for rent in star tower, lallubhai compound We are offering a 1bhk flat for rent in star tower, lallubhai compound, with the following features - 1 hall - 1 bedroom - 1 kitchen - Balcony and gallery with a nice view - Ample sunlight and fresh air - Daily water supply from 3 water tanks - Conveniently located near govandi and mankhurd railway stations - Nearby schools, markets,...', '1 BHK Flat for rent in Lallubhai Compound, Govandi East, Mumbai', 'Nagpur', 'Nagpur', 370, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(20, '2 BHK Flat for rent in Mulund West, Mumbai', 'Located in atmosphere o2, mulund west, this unfurnished 3 bhk apartment spans 754 sq.Ft. On the 47th floor of a high-Rise building. Available from april 15, 2026, it features 2 bathrooms, power backup, lift access, and facilities like a gym, swimming pool, and clubhouse. Close to mulund railway and m.P. Chowk metro stations, it offers excellent connectivity.', '2 BHK Flat for rent in Mulund West, Mumbai', 'Nagpur', 'Nagpur', 754, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(21, '2 BHK Flat for rent in Deonar, Chembur East', 'The appartment is sittuted at very rare location in mumbai city. The connectivity to area any of corner of mumbai is really good. You dont feel like u are living in the highly crowded city after reaching home. It is so isolate location at the same time very convenient to commute', '2 BHK Flat for rent in Deonar, Chembur East', 'Nagpur', 'Nagpur', 1000, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(22, '1 BHK Flat for rent in Azad Nagar, Chembur East', 'Very suitable place to stay, all connectivity like road, local and metro,', '1 BHK Flat for rent in Azad Nagar, Chembur East', 'Nagpur', 'Nagpur', 305, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(23, '2 BHK Flat for rent in Mulund West, Mumbai', 'Club house
Swimming pool
Touching nahur station and eastern express highway
Closer to hospital, schools, markets
Gated community
New society', '2 BHK Flat for rent in Mulund West, Mumbai', 'Nagpur', 'Nagpur', 618, 0, 'RENT', 'Flat', '2BHK', '[]', true, true, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(24, '2 BHK Flat for rent in Chandivali, Mumbai', 'A home that''s ready to welcome you | 2bhk on 6th floor, minal apartments, saki vihar road, andheri east 65,000/month | available 1st may 2026 | 980 sq ft + covered parking Some homes feel lived-In the moment you walk in. This is one of them. A bright, well-Maintained 2bhk on the 6th floor of minal apartments on saki vihar road, andheri east thoughtfully furnished, generously sized, and sitting ...', '2 BHK Flat for rent in Chandivali, Mumbai', 'Nagpur', 'Nagpur', 980, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(25, '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'This flat consists of 2 bathrooms build in 390 sq.Ft. Super built-Up area. This property is constructed on 390 sq.Ft. Located on 3rd of 16 floor. This is a ready to move property and it is 0-1 year old flat. This property is semi-Furnished. Equipped with 1 light. Ready to occupy from sat, 21 feb 2026, this property is ideal for family on any agreement type. We are demanding 33,000 for this unma...', '1 BHK Flat for rent in Ghatkopar East, Mumbai', 'Nagpur', 'Nagpur', 390, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(26, '1 BHK Flat for rent in Chunabhatti East, Sion, Mumbai', 'Available from april 15, 2026, this unfurnished 1 bhk flat spans 201 sq.Ft. On the 2nd floor of a 23-Story high-Rise at kings my homes, chunabhatti east, sion. The compact layout includes 1 bedroom and 1 bathroom. Residents benefit from parking, power backup, gym, lift, and rainwater harvesting, with multiple railway stations and a reputed school nearby.', '1 BHK Flat for rent in Chunabhatti East, Sion, Mumbai', 'Nagpur', 'Nagpur', 201, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(27, '1 BHK Flat for rent in Sardar Nagar, Sion, Mumbai', 'This property offers access to nearby landmarks and is close to hospital, close to market and close to railway station. This flat consists of 1 bathroom build in 320 sq.Ft. Carpet area. The flat is built on 320 sq.Ft. Area. Ease of access to 1 open parking within society. This flat is situated at top in a tower with 3 floors. This is a 10+ years old society. This property is semi-Furnished. Equ...', '1 BHK Flat for rent in Sardar Nagar, Sion, Mumbai', 'Nagpur', 'Nagpur', 320, 0, 'RENT', 'Flat', '1BHK', '[]', true, true, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(28, '2 BHK Flat for rent in Vaishali Nagar, Mulund West', 'This 2 bhk flat comes with 2 bathrooms set in 800 sq.Ft. Built-Up usable area. Flat is east-West facing the main road. Society has a garden with a play area for children and shiva temple inside the campus. The society has 24*7 security with cctv coverage. Balcony has been converted into a study room with book-Shelf and folding study table. Shopping centre , banks, atm, bus stop bang opposite th...', '2 BHK Flat for rent in Vaishali Nagar, Mulund West', 'Nagpur', 'Nagpur', 800, 0, 'RENT', 'Flat', '2BHK', '[]', true, true, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(29, '1 BHK Flat for rent in Chembur Colony, Chembur East', 'Best 1rk room near chembur colony bus stop , all market near , i want 1 male sharing with my 1rk flat which is suitable and affordable for every one', '1 BHK Flat for rent in Chembur Colony, Chembur East', 'Nagpur', 'Nagpur', 250, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(30, '1 BHK Flat for rent in Dharavi, Mumbai', 'Near by stations 5 minutes walking distance for king circle and gtb railways station 10 minutes walking for soin and mahim railway station 15 minutes walking for central and western matunga railway station. 5 minutes walking for any reachable bus stop and soin hospital.', '1 BHK Flat for rent in Dharavi, Mumbai', 'Nagpur', 'Nagpur', 280, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(31, '1 BHK Flat for rent in Mankhurd, Mumbai', 'I want to rent out a 1 bhk apartment available in mangal murti complex,mankhurd, central mumbai.Located in a serene place, it has a carpet area of 277 sq.Ft. It is an attractive property. The property has an amazing location and is unfurnished.It has 1 balcony(s) which offer an excellent view.', '1 BHK Flat for rent in Mankhurd, Mumbai', 'Nagpur', 'Nagpur', 277, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(32, '4 BHK Flat for rent in Powai, Mumbai', 'Located in kanakia silicon valley, powai, this 4 bhk flat spans 1368 sq.Ft on the 12th floor of a 24-Story high-Rise. Built 1-5 years ago, its semi-Furnished with 4 bedrooms and 4 bathrooms, available for rent from march 2026. Amenities include a gym, swimming pool, modular kitchen, power backup, and close proximity to ghatkopar stations and r city mall.', '4 BHK Flat for rent in Powai, Mumbai', 'Nagpur', 'Nagpur', 1368, 0, 'RENT', 'Flat', '4BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(33, '2 BHK Flat for rent in Chembur, Mumbai', 'I want to rent out a 2 bhk apartment available in shiv sagar enclave,chembur, central mumbai.Located in a serene place, it has a carpet area of 720 sq.Ft. It is an attractive property. The property has an amazing location and is unfurnished.It has 3 balcony(s) which offer an excellent view.', '2 BHK Flat for rent in Chembur, Mumbai', 'Nagpur', 'Nagpur', 720, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(34, '3 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'It''s fully furnished house withv3 bedrooms and a grand hall', '3 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Nagpur', 'Nagpur', 1588, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(35, '3 BHK Flat for rent in Ghatkopar East, Mumbai', 'Available immediately, this 3 bhk flat in dss shiv niwas, ghatkopar east spans 1000 sq.Ft. Situated on the 3rd floor of a mid-Rise, 5-10 year old building, it offers 3 bedrooms and 3 bathrooms. Semi-Furnished and air-Conditioned, its close to key religious sites and hospitals, blending comfort with convenience in central mumbai.', '3 BHK Flat for rent in Ghatkopar East, Mumbai', 'Nagpur', 'Nagpur', 1000, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(36, '3 BHK Flat for rent in Sindhu Wadi, Ghatkopar East', 'All amenities with luxury living 1 podium car parking , near by highway, upcoming metro , near station', '3 BHK Flat for rent in Sindhu Wadi, Ghatkopar East', 'Nagpur', 'Nagpur', 1150, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(37, '1 BHK Flat for rent in MHADA Colony 20, Powai', 'You can come and fill like home', '1 BHK Flat for rent in MHADA Colony 20, Powai', 'Nagpur', 'Nagpur', 350, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(38, '1 BHK Flat for rent in Netaji Nagar, Kurla, Mumbai', 'I want to rent out a 1 bhk apartment available in ashok nagar chs,chunabhatti, central mumbai.Located in a serene place, it has a carpet area of 120 sq.Ft. It is an attractive property. The property has an amazing location and is semi-Furnished.It has 1 balcony(s) which offer an excellent view.', '1 BHK Flat for rent in Netaji Nagar, Kurla, Mumbai', 'Nagpur', 'Nagpur', 120, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(39, '2 BHK Flat for rent in Chandivali, Mumbai', 'This flat consists of 2 bathrooms in 750 sq.Ft. Carpet area. This flat is constructed on 1000 sq.Ft. Area. This flat lies on the 4th floor of a 11 storey building. Well maintained 10+ years property. Semi-Furnished flat with 1 light, 1 fan, 1 wardrobe, 1 geyser and 1 modular kitchen. The flat will be available from fri, 03 apr 2026 for family on any agreement type. We are offering this property...', '2 BHK Flat for rent in Chandivali, Mumbai', 'Nagpur', 'Nagpur', 1000, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(40, '2 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Located in neelkanth kiran, garodia nagar, this furnished 2 bhk flat offers 750 sq.Ft. Of airy rooms with natural light on the top (3rd) floor of a low-Rise building. Ready for rent from january 10, 2026, it features 2 bathrooms, a modular kitchen, marble flooring, and parking. Close to schools, markets, hospital, railway station, and several religious sites.', '2 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Nagpur', 'Nagpur', 750, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(41, '1 BHK Flat for rent in Chembur, Mumbai', 'This flat consists of 2 bathrooms in 800 sq.Ft. Super built-Up area. This property is constructed on 800 sq.Ft. Located on 6th of 7 floor. This is a ready to move property and it is 1-5 years old flat. Semi-Furnished flat with 1 light. The flat will be available from sun, 29 mar 2026 for family on any agreement type. The expected rent is  30,000 monthly. Book this by paying only  750000 amount.', '1 BHK Flat for rent in Chembur, Mumbai', 'Nagpur', 'Nagpur', 800, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(42, '1 BHK Flat for rent in Kannamwar Nagar 2, Vikhroli East', 'Open-Air layout with unobstructed views, intercom facilities, and the entire building secured with cctv surveillance, along with biometric check-In and check-Out at the lobby entrance.', '1 BHK Flat for rent in Kannamwar Nagar 2, Vikhroli East', 'Nagpur', 'Nagpur', 375, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(43, '1 BHK Flat for rent in Laxmi Nagar, Vikhroli East', 'This flat consists of 2 bathrooms build in 497 sq.Ft. Carpet area. This property is constructed on 497 sq.Ft. Extra space for store room. You also get 2 covered parking inside the premises located on 13th of 17 floor. This property is semi-Furnished. Equipped with 2 ac, 2 geyser, 1 light, 1 fan and 1 water purifier. Property is ready to be leased on any agreement type from wed, 15 apr 2026 for ...', '1 BHK Flat for rent in Laxmi Nagar, Vikhroli East', 'Nagpur', 'Nagpur', 497, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(44, '2 BHK Flat for rent in Hariyali, Mumbai', 'Prime location, 2 min from easter express highway, 5 min from vikhroli railway station. Well connected wester mumbai, central mumbai, thane & navi mumbai. Near by market, schools, hotels, hospitals.', '2 BHK Flat for rent in Hariyali, Mumbai', 'Nagpur', 'Nagpur', 581, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(45, '2 BHK Flat for rent in Deonar, Chembur East', 'Located on the first floor of a low-Rise building in oak shade, deonar, this 2 bhk flat spans 800 sq.Ft. Semi-Furnished and over 10 years old, it features airy, east-Facing rooms with ceramic flooring and a modular kitchen. Immediate availability makes it ideal for those seeking proximity to markets, temples, and the railway station in central mumbai.', '2 BHK Flat for rent in Deonar, Chembur East', 'Nagpur', 'Nagpur', 800, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(46, '1 BHK Flat for rent in Chandivali, Mumbai', 'Fully furnished, newly renovated studio ideal for working professionals (Preferably air hostess / female tenants) Recently renovated and tastefully furnished home, designed for comfort and convenience. Perfect for working professionals seeking a clean, modern, and move-In-Ready space. Key features: Blue star split ac Sofa-Cum-Bed Refrigerator Geyser Spacious wardrobe Modular kitchen with gas st...', '1 BHK Flat for rent in Chandivali, Mumbai', 'Nagpur', 'Nagpur', 225, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(47, '2 BHK Flat for rent in Bhandup West, Mumbai', 'Inside society Vegetable and fruit shop Hospital Laundry Gym Children park Adults park Grocery shop Temple Church Outside society Fish market Chicken market Hotels Hospital School Stationery shop Nearby Nahur station - 5 min walking Eastern expressway highway - 10min Lbs marg - 5-6min Fortis hospital - 7-8min Dmart -7-8min Mulund goregaon link road - 6-7 min Connectivity - Navimumbai ,thane , p...', '2 BHK Flat for rent in Bhandup West, Mumbai', 'Nagpur', 'Nagpur', 1000, 0, 'RENT', 'Flat', '2BHK', '[]', true, true, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(48, '2 BHK Flat for rent in Kurla East, Mumbai', 'Nearest to kurla railway station.
Around 15-20mins to reach airport', '2 BHK Flat for rent in Kurla East, Mumbai', 'Nagpur', 'Nagpur', 562, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(49, '3 BHK Flat for rent in Vikhroli East, Mumbai', 'It is outside facing, well maintained apartment with interior done well for owner''s living -False ceiling, show rack, full size wardrobes, furnished kitchen electrical fitting, profile lights and storage. Kids room has transparent door. Carpet area is 1100 sqft', '3 BHK Flat for rent in Vikhroli East, Mumbai', 'Nagpur', 'Nagpur', 1271, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(50, '3 BHK Flat for rent in Bhandup West, Mumbai', 'This flat consists of 3 bathrooms in 1350 sq.Ft. Super built-Up area. Flat is constructed on 1350 sq.Ft. Placed on 15th of 16 floor in 0-1 year old tower. Unfurnished flat the flat will be available from tue, 17 mar 2026 for family on any agreement type. We are demanding  55,000 for this unmatched property.', '3 BHK Flat for rent in Bhandup West, Mumbai', 'Nagpur', 'Nagpur', 1350, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(51, '2 BHK Flat for rent in Hiranandani Gardens Powai, Mumbai', 'Enough space compared to other projects around, every day to day necessity things are within walking distance.', '2 BHK Flat for rent in Hiranandani Gardens Powai, Mumbai', 'Nagpur', 'Nagpur', 1050, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(52, '3 BHK Flat for rent in Ghatkopar East, Mumbai', 'This furnished 3 bhk flat spans 950 sq.Ft. On the 6th floor of a high-Rise at gurukrupa divyam, ghatkopar east. Built 1-5 years ago, it offers modular kitchen, central ac, power backup, and access to gym, clubhouse, and pool. Available from march 2026, it benefits from nearby ghatkopar station, metro, schools, and shopping centers.', '3 BHK Flat for rent in Ghatkopar East, Mumbai', 'Nagpur', 'Nagpur', 950, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(53, '2 BHK Flat for rent in Rambaug, Chandivali', 'This flat offers a view of powai lake and is situated right along the jvlr highway; Furthermore, a metro station is located right next to the society gate.Near powai iit mumbai.', '2 BHK Flat for rent in Rambaug, Chandivali', 'Nagpur', 'Nagpur', 706, 0, 'RENT', 'Flat', '2BHK', '[]', true, true, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(54, '1 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'It is on the 3rd floor of a conveniently located building in ghatkopar (e). The building is old and has no lift.', '1 BHK Flat for rent in Garodia Nagar, Ghatkopar East', 'Nagpur', 'Nagpur', 380, 0, 'RENT', 'Flat', '1BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(55, '2 BHK Flat for rent in Mulund East, Mumbai', 'This flat consists of 2 bathrooms in 925 sq.Ft. Super built-Up area. The flat is built on 925 sq.Ft. Area. This flat is situated at 4th in a tower with 7 floors. This is a 1-5 years old society. It is a semi-Furnished property. Inclusive of 1 light. The flat will be available from wed, 01 apr 2026 for family on any agreement type. With all the highlighted features, we are asking for 30,000 mont...', '2 BHK Flat for rent in Mulund East, Mumbai', 'Nagpur', 'Nagpur', 925, 0, 'RENT', 'Flat', '2BHK', '[]', true, true, 'Semi-Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(56, '3 BHK Flat for rent in Pirojshanagar, Vikhroli East', 'I want to rent out a 3 bhk apartment available in godrej trilogy,worli, mumbai south.Located in a serene place, it has a carpet area of 1190 sq.Ft. It is an attractive property. The property has an amazing location and is furnished.', '3 BHK Flat for rent in Pirojshanagar, Vikhroli East', 'Nagpur', 'Nagpur', 1276, 0, 'RENT', 'Flat', '3BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(57, '2 BHK Flat for rent in Hiranandani Gardens Powai, Mumbai', 'This furnished 2 bhk flat spans 1000 sq.Ft. On the 15th floor of a 22-Story high-Rise in hiranandani castle rock, powai. Available immediately, it includes two bathrooms and comes with a modular kitchen, central ac, and access to a gym, clubhouse, and swimming pool. Conveniently located near vikhroli railway station and mogra metro.', '2 BHK Flat for rent in Hiranandani Gardens Powai, Mumbai', 'Nagpur', 'Nagpur', 1000, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Unfurnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0),
(58, '2 BHK Flat for rent in Chunabhatti, Sion, Mumbai', 'Spacious 2bhk fully furnished flat near bkc | ideal for working professionals
Fully furnished ready to move in
Prime location near bkc (5 mins drive)
Close to major hospital and daily conveniences
Ground floor easy access
Suitable for working professionals / small family', '2 BHK Flat for rent in Chunabhatti, Sion, Mumbai', 'Nagpur', 'Nagpur', 715, 0, 'RENT', 'Flat', '2BHK', '[]', true, false, 'Furnished', 'RENT', 1, CURRENT_TIMESTAMP, '', '', false, false, false, false, false, false, false, 0);